### ISSUE TITLE
Is there a place to config the listener so that mmbot listen to @xxx instead of @mmbot?

### ISSUE THREAD

**Issue by wonderxboy** [mmbot/mmbot#195]
Hi,

Can I change the config so that mmbot listens to other handle (say @somebot) than "@mmbot"?
If not, how would you recommend to achieve that?

**Comment by PeteGoo** [comment]
Yes that should be possible. Set the MMBOT_ROBOT_NAME variable in the config file

**Comment by wonderxboy** [comment]
Cool, that worked. Thanks

**Comment by PeteGoo** [comment]
Awesome
