### ISSUE TITLE
Bot name in config is not working.

### ISSUE THREAD

**Issue by GhostTW** [mmbot/mmbot#198]
got question here,
I found slack adapter config has a setting `BOTNAME` , but it didn't work.
the only way to set the bot name in config is in RobotBuilder.cs line 117 `MMBOT_ROBOT_NAME`
but there has no describe about it.
If it is a issue , I would add a basic `ROBOT` section to wiki and remove `BOTNAME` in SLACK section.

**Comment by GhostTW** [comment]
edit wiki page
* [Add basic robot config describe.](https://github.com/mmbot/mmbot/wiki/Configuring-mmbot/bd59c9db75e4272e7f023b99851a86ec10a013d9)

* [Remove slack bot name config.](https://github.com/mmbot/mmbot/wiki/Configuring-mmbot/0f1cd04ab0e978f2039337603d9808031b2a4f29)

**Comment by PeteGoo** [comment]
Thanks, these doco changes are perfect.

The way the configuration works is the format MMBOT_<SECTION>_<SETTING>. i.e. the following mmbot.ini file

```
[ROBOT]
NAME = mmbot
```

will result in a configuration variable MMBOT_ROBOT_NAME that can be read from code.

**Comment by GhostTW** [comment]
English is not my native language, sorry that I can not fully understand what you mean.

Do you mean I would add better describe in `mmbot.ini` ?

fix it if you feel it not good , thanks :D

**Comment by PeteGoo** [comment]
No, it's good. :thumbsup:
