### ISSUE TITLE
Auth config admins is not working

### ISSUE THREAD

**Issue by GhostTW** [mmbot/mmbot#200]
In `Auth.csx` doco

```c#
* <configuration>
*    MMBOT_AUTH_ADMINS : a comma seperated list of admins
* </configuration>
```

but the code in `MMBot.Core.Robot` line 92 is `GetConfigVariable("MMBOT_AUTH_ADMIN")`
this code makes auth config not working, I will edit `Auth.csx` doco and send PR.

**Comment by PeteGoo** [comment]
Awesome. Thanks
