### ISSUE TITLE
Mmbot not responding to @botname with Slack Adapter

### ISSUE THREAD

**Issue by jachin84** [mmbot/mmbot#204]
I've tested the following:
* hal open the pod bay doors
* HAL: open the pod bay doors
* @HAL open the pod bay doors

The first two work, @HAL doesn't work, at least not in the Slack Adapter. I've had a quick look through the code but couldn't find where to change this.

**Comment by PeteGoo** [comment]
I think the secret will be here

https://gitter.im/mmbot/mmbot?at=55ae14a2ea4b0b3b25a504fe
